close all
clear all

%
% This script adds trail to the particle file generated by the particle
% tracking code.
%
% The source particle file (output of the particle tracking code)
% is called src_file, and the output file of this script with added
% trail particles is called src_file.
%
% After you run the particle tracking code, run this script to get
% a new particle file with added trail.
%
src_file = 'src.pth.nc';
dst_file = 'dst.pth.nc';

%
% Number of particles.
%
n_tail = 15;
n_tail = n_tail + 1;

src_info = ncinfo(src_file);

src_dim1 = src_info.Dimensions(1);
src_dim2 = src_info.Dimensions(2);
n_src_pts = src_dim2.Length;
dst_dim2 = src_dim2;
n_dst_pts = src_dim2.Length * n_tail;
dst_dim2.Length = n_dst_pts;

src_time = ncread(src_file,src_info.Variables(1).Name);
src_x = ncread(src_file,src_info.Variables(2).Name);
src_y = ncread(src_file,src_info.Variables(3).Name);
src_z = ncread(src_file,src_info.Variables(4).Name);
src_pper_time = ncread(src_file,src_info.Variables(5).Name);
%
dst_mode = netcdf.getConstant('NETCDF4');
dst_mode = bitor(dst_mode, netcdf.getConstant('CLASSIC_MODEL'));
dst_id = netcdf.create(dst_file, dst_mode);
global_varid = netcdf.getConstant('GLOBAL');
netcdf.putAtt(dst_id,global_varid,'_FillValue', -99999);
%
dst_dim_id1 = netcdf.defDim(dst_id, 'ntimesnap', ...
    src_dim1.Length);
dst_dim_id2 = netcdf.defDim(dst_id, 'nparticle', ...
    dst_dim2.Length);
%
dst_var1 = netcdf.defVar(dst_id, src_info.Variables(1).Name, ...
    'NC_DOUBLE', dst_dim_id1);
%
dst_var2 = netcdf.defVar(dst_id, src_info.Variables(2).Name, ...
    'NC_DOUBLE', [dst_dim_id2, dst_dim_id1]);
netcdf.putAtt(dst_id, dst_var2, '_FillValue', -99999);
%
dst_var3 = netcdf.defVar(dst_id, src_info.Variables(3).Name, ...
    'NC_DOUBLE', [dst_dim_id2, dst_dim_id1]);
netcdf.putAtt(dst_id, dst_var3, '_FillValue', -99999);
%
dst_var4 = netcdf.defVar(dst_id, src_info.Variables(4).Name, ...
    'NC_DOUBLE', [dst_dim_id2, dst_dim_id1]);
netcdf.putAtt(dst_id, dst_var4, '_FillValue', -99999);
%
dst_var5 = netcdf.defVar(dst_id, src_info.Variables(5).Name, ...
    'NC_INT', dst_dim_id1);
netcdf.putAtt(dst_id, dst_var5, '_FillValue', int32(0));
%
netcdf.endDef(dst_id);
netcdf.putVar(dst_id, dst_var1, src_time);
%
nc_temp = repmat(src_x, n_tail, 1);
for i = 1 : src_dim1.Length - 1
    nc_temp_i = ...
        nc_temp((n_tail - 1) * n_src_pts + 1 : n_tail * n_src_pts, i);
    for j = i + 1 : min(src_dim1.Length, i + n_tail - 1)
        j1 = j - i + 1;
        nc_temp((n_tail - j1) * n_src_pts + 1  : ...
            (n_tail - j1 + 1) * n_src_pts, j) = ...
            nc_temp_i;            
    end
end
netcdf.putVar(dst_id, dst_var2, nc_temp);
%
% An alternative way, with less memory consumption. %
%
% for i = 1 : src_dim1.Length
%     nc_temp = repmat(src_x(:, i), src_dim1.Length, 1);
%     netcdf.putVar(dst_id, dst_var2, [0,i-1], [n_dst_pts,1], nc_temp);
% end
%
nc_temp = repmat(src_y, n_tail, 1);
for i = 1 : src_dim1.Length - 1
    nc_temp_i = ...
        nc_temp((n_tail - 1) * n_src_pts + 1 : n_tail * n_src_pts, i);
    for j = i + 1 : min(src_dim1.Length, i + n_tail - 1)
        j1 = j - i + 1;
        nc_temp((n_tail - j1) * n_src_pts + 1  : ...
            (n_tail - j1 + 1) * n_src_pts, j) = ...
            nc_temp_i;            
    end
end
netcdf.putVar(dst_id, dst_var3, nc_temp);
%
nc_temp = repmat(src_z, n_tail, 1);
for i = 1 : src_dim1.Length - 1
    nc_temp_i = ...
        nc_temp((n_tail - 1) * n_src_pts + 1 : n_tail * n_src_pts, i);
    for j = i + 1 : min(src_dim1.Length, i + n_tail - 1)
        j1 = j - i + 1;
        nc_temp((n_tail - j1) * n_src_pts + 1  : ...
            (n_tail - j1 + 1) * n_src_pts, j) = ...
            nc_temp_i;            
    end
end
netcdf.putVar(dst_id, dst_var4, nc_temp);
clear nc_temp;
%
dst_pper_time = n_tail * src_pper_time;
netcdf.putVar(dst_id, dst_var5, dst_pper_time);
%
netcdf.close(dst_id);
